### ISSUE TITLE
Always unavailable entities

### ISSUE THREAD

**Issue by fusionstream** [DigitallyRefined/ha-cloudflare-speed-test#28]
Hi.

I seem unable to get any values from this add on.

I've installed it via HACs, added it via the integrations page, but it remains always unavailable.

Is a step missing from the readme?

I am able to visit the cloudflare webpage directly and that runs fine

**Comment by DigitallyRefined** [comment]
From the logs it sounds like it could be an issue with the [`cfspeedtest` dependancy](https://github.com/martinbrose/cloudflarepycli), as it looks like some metadata like region can sometimes be missing.

It seems like there was already a PR raised to fix this issue in https://github.com/martinbrose/cloudflarepycli/pull/28 which was merged, but not released to [PyPI](https://pypi.org/project/cloudflarepycli/).

You should be able to test the fix in your local Home Assistant instance by editing the file:

`/config/custom_components/cloudflare_speed_test/manifest.json`

```diff
@@ -11,3 +11,3 @@
   "requirements": [
-    "cloudflarepycli==2.0.2"
+    "cloudflarepycli @ git+https://github.com/martinbrose/cloudflarepycli@c13517b9d9031c4ec1552a76c848e36ba2dd094f"
   ],
```

Could you try switching this requirement manually and restart Home Assistant, then let me know if this version works.
If it does, I can release a new version updating to this version 🤞

**Comment by fusionstream** [comment]
Could it be that the patch branch has since been deleted?

**Comment by DigitallyRefined** [comment]
I've published a `0.0.3-dev` build that hopefully should fix it 🤞 

Could you try installing it from HACS, restarting Home Assistant and see if it works:

<img width="1719" height="795" alt="Image" src="https://github.com/user-attachments/assets/5fa7570a-8c29-4688-8e4a-5c58fa857c44" />

<img width="1722" height="798" alt="Image" src="https://github.com/user-attachments/assets/ca707f13-2825-4c1e-9284-a0b5d498e221" />

<img width="1125" height="1226" alt="Image" src="https://github.com/user-attachments/assets/b0931d38-9ecc-4dcb-862b-2d9c54e7a9c8" />

**Comment by DigitallyRefined** [comment]
I've published a new `0.0.3-dev2` build, maybe 3rd time lucky? 🤞 Could you let me know if you get any errors from this version? 🙏

**Comment by fusionstream** [comment]
Sorry mate. Missed this message. Still doesn't work for me I'm afraid. Exact same region key error. Am running the released 0.0.3 as I dont' see any -dev3 build

**Comment by fusionstream** [comment]
Thanks for the help and fix! :)
